# Generated by Django 5.0.7 on 2024-08-02 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('lic', models.CharField(max_length=20, unique=True)),
                ('state', models.CharField(max_length=15)),
                ('equipment', models.CharField(max_length=50)),
                ('total_miles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NewDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150, unique=True)),
                ('lastname', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('lic', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('expire', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('dispatcher', 'Dispatcher'), ('driver', 'Driver')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_time', models.DurationField()),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_destination', to='truckdash.location')),
                ('origin_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_origin', to='truckdash.location')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=15, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='truckdash.location')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truckdash.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truckdash.route')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truckdash.truck')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truckdash.truck')),
            ],
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fuel_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='truckdash.location')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truckdash.truck')),
            ],
        ),
    ]
